apiVersion: v1
kind: ConfigMap
metadata:
  name: app-pedidos-config
data:
  DATASOURCE_URL: "jdbc:mysql://fiap-fastfood-pedidos-aurora-instance-1.cvepqcjgr17y.us-east-1.rds.amazonaws.com:3306/fiapfastfoodPedidos"
  MARIADB_DATABASE: "fiapfastfoodPedidos"
  PRODUTOS_API_URL: ""
  PESSOAS_API_URL: ""