apiVersion: v1
kind: ConfigMap
metadata:
  name: app-pedidos-config
data:
  DATASOURCE_URL: "jdbc:mysql://fiap-fastfood-pedidos-aurora-instance-1.c0sgdyfdxjwh.us-east-1.rds.amazonaws.com:3306/fiapfastfoodPedidos"
  MARIADB_DATABASE: "fiapfastfoodPedidos"
  PRODUTOS_API_URL: "http://a84495a98ea614a438ed43fa662843bb-2103026305.us-east-1.elb.amazonaws.com"
  PESSOAS_API_URL: "http://a24a36633e830453798988a0613dcb98-576010307.us-east-1.elb.amazonaws.com"


